version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_CLIENT_CERT=${KAFKA_CLIENT_CERT}
      - KAFKA_CLIENT_CERT_KEY=${KAFKA_CLIENT_CERT_KEY}
      - KAFKA_TRUSTED_CERT=${KAFKA_TRUSTED_CERT}
      - KAFKA_PREFIX=${KAFKA_PREFIX}
      - GRAFANA_CLOUD_URL=${GRAFANA_CLOUD_URL}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
    ports:
      - "${PORT:-3000}:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  continuous-insert:
    build: .
    command: node dist/scripts/continuous-insert.js
    depends_on:
      - app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_CLIENT_CERT=${KAFKA_CLIENT_CERT}
      - KAFKA_CLIENT_CERT_KEY=${KAFKA_CLIENT_CERT_KEY}
      - KAFKA_TRUSTED_CERT=${KAFKA_TRUSTED_CERT}
      - KAFKA_PREFIX=${KAFKA_PREFIX}
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - ./docker/exporters/mongodb_exporter:/exporters/mongodb_exporter
      - ./docker/exporters/kafka_exporter:/exporters/kafka_exporter
    ports:
      - "9090:9090"
    environment:
      - GRAFANA_CLOUD_URL=${GRAFANA_CLOUD_URL}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./docker/grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
  
  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "9216:9216"

  kafka_exporter:
    image: danielqsj/kafka-exporter:latest
    environment:
      - KAFKA_SERVER=${KAFKA_BROKERS}
    ports:
      - "9308:9308"

volumes:
  prometheus_data:
  grafana_data: