networks:
  app_network:
    name: pulse-flow_app_network

services:
  app:
    networks:
      - app_network
    container_name: pulse-flow-app
    image: ghcr.io/${GITHUB_REPOSITORY:-pulse-flow}:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning

volumes:
  prometheus_data: