version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    ports:
      - "${PORT}:3000"
    healthcheck:
      test: ["CMD", "node", "./healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./docker/prometheus/prometheus.yml/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./docker/grafana:/etc/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus