services:
  app:
    build:
      context: .
      target: development
    container_name: pulse-flow-app-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "3000:3000"
    command: npm run dev

  continuous-insert:
    build:
      context: .
      target: development
    container_name: pulse-flow-inserter-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
    command: npm run dev:insert

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dev
    volumes:
      - ./docker/grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  prometheus_data:
  grafana_data: