services:
  - type: web
    name: pulse-flow
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GRAFANA_PROMETHEUS_URL
        sync: false
      - key: GRAFANA_PUSH_URL
        sync: false
      - key: GRAFANA_USERNAME
        sync: false
      - key: GRAFANA_API_KEY
        sync: false
      - key: PORT
        value: 3000
      - key: RABBITMQ_URL
        sync: false
      - key: RABBITMQ_PASSWORD
        sync: false
    healthCheckPath: /healthz
    healthCheckTimeout: 5
    autoDeploy: true
    numInstances: 1
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    sleepPreventionEnabled: true
    sleepPreventionInterval: 1
    gracefulShutdownTimeout: 5000
    restartPolicyType: ON_FAILURE
    restartPolicyMaxRetries: 3
    buildFilter:
      paths:
        - src/**/*.ts
        - package.json
        - package-lock.json
        - tsconfig.json
  - type: worker
    name: pulse-flow-heartbeat
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/scripts/heartbeat.js
    envVars:
      - key: APP_URL
        value: https://pulse-flow.onrender.com
      - key: HEARTBEAT_INTERVAL
        value: 300000  # Reduced to 5 minutes
    sleepPreventionEnabled: true
    restartPolicyType: ALWAYS