services:
  - type: web
    name: pulse-flow
    env: docker
    buildCommand: docker build -t pulse-flow .
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - package.json
        - Dockerfile
        - docker-compose.yml
      ignoredPaths:
        - .git/**
        - README.md
        - docs/**
        - .env