jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
  remotingSecurity:
    enabled: true

jobs:
  - script: >
      pipelineJob('pulse-flow-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITHUB_REPOSITORY}')
                  credentials('github-creds')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }