global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pulse-flow'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scheme: 'http'

remote_write:
  - url: "https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom/push"
    basic_auth:
      username: "${GRAFANA_INSTANCE_ID}"
      password: "${GRAFANA_API_TOKEN}"