global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pulse-flow'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scheme: 'http'

remote_write:
  - url: "${GRAFANA_PUSH_URL}"
    basic_auth:
      username: "${GRAFANA_USERNAME}"
      password: "${GRAFANA_API_TOKEN}"