global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pulse-flow'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scheme: 'http'

remote_write:
  - url: "${GRAFANA_CLOUD_URL}/api/prom/push"
    basic_auth:
      username: "api_key"
      password: "${GRAFANA_API_KEY}"