global:
  scrape_interval: 15s
  external_labels:
    monitor: 'pulse-flow'

scrape_configs:
  - job_name: 'pulse-flow'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scheme: 'http'

remote_write:
  - url: "${GRAFANA_PUSH_URL}"
    headers:
      X-Scope-OrgID: "${GRAFANA_USERNAME}"
    authorization:
      type: Bearer
      credentials: "${GRAFANA_API_KEY}"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'pulse_flow_.+'
        action: keep