global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pulse-flow'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scheme: 'http'

remote_write:
  - url: "http://prometheus:9090/api/prom/push"
    basic_auth:
      username: "${GRAFANA_API_KEY}"
      password: "${GRAFANA_API_KEY}"