name: Deploy to Production

on:
  push:
    branches:
      - feat/jenkins
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  JENKINS_ADMIN_ID: admin
  JENKINS_ADMIN_PASSWORD: ${{ secrets.JENKINS_ADMIN_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Test MongoDB Connection
        run: |
          echo "Testing MongoDB connection..."
          echo "MONGODB_URI is set: ${{ secrets.MONGODB_URI != '' }}"
          npm run test:mongodb
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create environment file
        run: |
          cat > .env << 'EOL'
          PORT=3000
          NODE_ENV=production
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          GRAFANA_CLOUD_URL=${{ secrets.GRAFANA_CLOUD_URL }}
          GRAFANA_API_KEY=${{ secrets.GRAFANA_API_KEY }}
          EOL

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Setup Network and Volumes
        run: |
          docker network create pulse-flow_app_network || true
          docker volume create jenkins_home || true
          docker volume create prometheus_data || true
          docker volume create grafana_data || true

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.prod.yml up -d
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GRAFANA_CLOUD_URL: ${{ secrets.GRAFANA_CLOUD_URL }}
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          JENKINS_ADMIN_ID: ${{ env.JENKINS_ADMIN_ID }}
          JENKINS_ADMIN_PASSWORD: ${{ env.JENKINS_ADMIN_PASSWORD }}

      - name: Wait for Jenkins
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "200" ]]; do sleep 5; done' || false

      - name: Configure Jenkins
        run: |
          # Get Jenkins CLI
          wget http://localhost:8080/jnlpJars/jenkins-cli.jar

          # Create Jenkins API token
          curl -X POST \
            -u "${JENKINS_ADMIN_ID}:${JENKINS_ADMIN_PASSWORD}" \
            -H "Content-Type: application/json" \
            --data '{"newTokenName": "github-actions"}' \
            http://localhost:8080/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken

          # Install suggested plugins
          java -jar jenkins-cli.jar -s http://localhost:8080/ \
            -auth ${JENKINS_ADMIN_ID}:${JENKINS_ADMIN_PASSWORD} \
            install-plugin workflow-aggregator git github docker-workflow

      - name: Create Jenkins Pipeline
        run: |
          java -jar jenkins-cli.jar -s http://localhost:8080/ \
            -auth ${JENKINS_ADMIN_ID}:${JENKINS_ADMIN_PASSWORD} \
            create-job pulse-flow-pipeline < jenkins/job.xml

      - name: Verify Deployment
        run: |
          echo "Checking service status..."
          docker-compose ps
          
          echo "Checking Jenkins..."
          curl -f http://localhost:8080/login
          
          echo "Checking app..."
          curl -f http://localhost:3000/healthz