name: Deploy to Production

on:
  push:
    branches:
      - feat/cloud-deployment
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Test MongoDB Connection
        run: |
          echo "Testing MongoDB connection..."
          echo "MONGODB_URI is set: ${{ secrets.MONGODB_URI != '' }}"
          npm run test:mongodb
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create environment file
        run: |
          cat > .env << 'EOL'
          PORT=3000
          NODE_ENV=production
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          GRAFANA_CLOUD_URL=${{ secrets.GRAFANA_CLOUD_URL }}
          GRAFANA_API_KEY=${{ secrets.GRAFANA_API_KEY }}
          EOL

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version


      - name: Deploy with Docker Compose
        run: |
          docker network create pulse-flow_app_network || true
          docker-compose -f docker-compose.prod.yml up -d
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GRAFANA_CLOUD_URL: ${{ secrets.GRAFANA_CLOUD_URL }}
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
